### ISSUE TITLE
Accessibility fixes/improvements

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#1015]
- Feedback form:
  - [ ] combine the prompt at the top into one element
  - [ ] adjust the placeholder of the input so it’s shorter?
  - [ ] add a secondary action to the screenshot and URL inputs to activate their buttons
- [ ] Reorder the URL bar icons in accessibility so the label comes first #1055
- [ ] Provide an easy way to jump to the landmarks of the screen? (URL bar, content, toolbar) #1055
  - look into making the URL bar seem like it’s in landscape mode a11y-navigation-wise?
- [ ] Add a hint or secondary action to the back/forward buttons to allow users to activate the sheet
- [ ] Add a hint to buttons with a long-press menu (reload, tabs, new tab in tab tray)
  - Safari uses “Double tap and hold for more Tab Options” but the docs discourage the use of terms that imply specific interaction methods
  - maybe put the actions as accessibility actions? Then users can swipe up or down to access them
- [ ] debug accessibility frames getting offset in URL bar (when scrolling down?)
- [ ] Add an accessible title to the tracking protection popover?
- “You are incognito” card
  - [ ] hide the image at the top
  - [ ] mark the first label as a heading?
  - [ ] Consider how to combine the further labels?
- Account settings
  - [ ] fix how “@neeva.co” and similar are read — maybe do `s/\./ dot /g`?
- Default browser
  - [ ] Mark the “Switch Your Default Browser” text as a heading
  - [ ] hide the image
- Clear Browsing Data
  - [ ] the red action button has an empty heading before it — this is an OS bug we should consider reporting (if it’s still a problem on iOS 15)
- Overlay sheet
  - [ ] Fix overlay sheet dismiss button being selected by default (forcing users to navigate backwards which is unnatural)
  - [ ] Mark the title of the overlay sheet as a heading
  - [ ] Label the “Save To Spaces” spaces as “Add to {name}” ? (or put that as a hint?)
  - [ ] Label shared/public spaces with appropriate hints
- [ ] Relabel incognito toggle button (see also #1014)

**Comment by jedireza** [comment]
> Relabel incognito toggle button

I think this can be checked off. Looks like it was resolved via #2942
